### ISSUE TITLE
Add an example of client-side routing

### ISSUE THREAD

**Issue by dan2k3k4** [AmazeeLabs/gatsby-starter-amazee#52] opened 2020-04-06 12:47 UTC
As it is more likely that some of our projects will need an authentication layer with client-side routing, we should build an example to make it easier to get started with this setup.

`import { Router } from '@reach/router';`

And inside the component which will act as the "main" parent component:
```
<Router path="/blog/*">
  <Edit path="/:blogID/edit" />
  <Delete path="/:blogID/delete" />
</Router>
```
Thus `/blog/1` would be statically built and served by Gatsby, but `/blog/1/edit` would be a client-side only route which perhaps requires authentication to view it and edit the contents to update the blog (which may trigger a `gatsby build` for instance).

Something like this could either be documented or an actual implementation could be added to this starter project.

**Comment by JohnAlbin** [comment] 2020-06-04 10:36
Duplicate of #23

**Closed by JohnAlbin** 2020-06-04 10:36 UTC
